issue2551042 - add extra \ to \w in raw string url_to_regex. Not sure why this is needed. Maybe something changed in how raw strings are interpreted? Without patch causes crash:
 re.error: bad escape \w at position 2

under python 3.7

Also tried to add python 3.7 (hopefully 3.7.3) to travis.