Prevent AttributeError when removing all roles of a user
When making the entry field empty newvalues.get('roles') is None, causing:
AttributeError: 'NoneType' object has no attribute 'split'