issue2551126 - AttributeError: 'str' object has no attribute 'local'.
Fix traceback caused by DateHTMLProperty.pretty() called
on a string value due to error in some other field.